export * from './lib/services/gallery-ref';
export * from './lib/nav/gallery-nav.component';
export * from './lib/thumbs/gallery-thumbs.component';
export * from './lib/bullets/gallery-bullets.component';
export * from './lib/counter/gallery-counter.component';
export * from './lib/utils/img-recognizer';
export * from './lib/core/gallery.component';
export * from './lib/templates/items.model';
export * from './lib/templates/gallery-image.component';
export * from './lib/models/config.model';
export * from './lib/models/constants';
export * from './lib/gallery.module';
export * from './lib/directives/gallery-item-def.directive';
export * from './lib/directives/gallery-box-def.directive';
export * from './lib/utils/item.class';
// export * from './lib/templates/gallery-iframe.component';
// export * from './lib/templates/gallery-video.component';
// export * from './lib/autoplay/autoplay.directive';
// export * from './lib/auto-height/auto-height';
