import { coreVersion, compareCore, normalizeManifestEntry } from '../projects/ng-gallery/.storybook/addons/version-addon/version-utils.ts';

function runTestSuite() {
  console.log('🧪 RUNNING ANGULAR MATERIAL STYLE VERSION SWITCHER EMULATION\n');

  // Realistic deep-history manifest generated by your CI workflow
  const deepHistoryManifest = [
    { "path": "next", "version": "14.0.0-next.0" },
    { "path": "13.0.1", "version": "13.0.1" },
    { "path": "13.0.0", "version": "13.0.0" },
    { "path": "12.0.3", "version": "12.0.3" },
    { "path": "12.0.0", "version": "12.0.0" },
    { "path": "11.1.2", "version": "11.1.2" }
  ];

  console.log('📦 Given the historical versions.json manifest state:');
  console.log(JSON.stringify(deepHistoryManifest, null, 2));
  console.log('\n--------------------------------------------------\n');

  // Test Case A: User visiting the active stable 13.0.1 page
  emulateStorybookRuntime({
    scenarioName: 'User browsing active stable 13.0.1 environment',
    isLocalhost: false,
    windowLocationPathname: '/ngx-gallery/13.0.1/',
    mockManifest: deepHistoryManifest
  });

  // Test Case B: User visiting an older v12 documentation track
  emulateStorybookRuntime({
    scenarioName: 'User browsing older historical 12.0.3 environment',
    isLocalhost: false,
    windowLocationPathname: '/ngx-gallery/12.0.3/',
    mockManifest: deepHistoryManifest
  });
}

function emulateStorybookRuntime({ scenarioName, isLocalhost, windowLocationPathname, mockManifest }) {
  console.log(`🏃 SCENARIO: ${scenarioName}`);

  const currentPath = windowLocationPathname;
  const pathSegments = currentPath.split('/').filter(Boolean);
  const repoName = pathSegments[0] || 'ngx-gallery';
  const activeFolderOnServer = pathSegments[1] || 'Local';

  const dynamicVersionItems = [];

  if (isLocalhost) {
    dynamicVersionItems.length = 0;
    dynamicVersionItems.push({ value: 'Local', title: 'Local' });
  } else {
    const entries = mockManifest
      .map((item) => normalizeManifestEntry(item))
      .filter(e => e.version && e.version.trim().length > 0);

    const stable = entries.filter(e => !/-/.test(e.version));
    const prereleases = entries.filter(e => /-/.test(e.version) || e.isNext);

    // 1. Identify the absolute highest stable entry
    let latestStable = stable.slice().sort((a, b) => compareCore(b.version, a.version))[0];
    if (!latestStable && entries.length > 0) {
      latestStable = entries[0];
    }

    const explicitNext = entries.find(e => e.id === 'next');
    const highestPrerelease = prereleases.slice().sort((a, b) => compareCore(b.version, a.version))[0];
    const nextEntry = explicitNext || highestPrerelease;

    const items = [];

    // 2. Next goes on top ONLY if core version > latest stable core
    if (nextEntry && latestStable) {
      if (compareCore(nextEntry.version, latestStable.version) > 0) {
        items.push({ value: nextEntry.id, title: 'Next' });
      }
    } else if (nextEntry && !latestStable) {
      items.push({ value: nextEntry.id, title: 'Next' });
    }

    // 3. Absolute latest stable entry is pinned next: "13.0.1 (latest)"
    if (latestStable) {
      items.push({ value: latestStable.id, title: `${latestStable.version} (latest)` });
    }

    // 4. Group remaining stables by major version and find the highest available patch for each major track
    const byMajor = new Map();
    stable.forEach(e => {
      const major = coreVersion(e.version).parts[0] || 0;
      const existing = byMajor.get(major);
      // Keep track of the highest patch version for this major track
      if (!existing || compareCore(e.version, existing.version) > 0) {
        byMajor.set(major, { id: e.id, version: e.version });
      }
    });

    // 5. Sort majors descending and exclude latestStable's major track to prevent duplicates
    const latestMajor = latestStable ? coreVersion(latestStable.version).parts[0] : null;
    Array.from(byMajor.entries())
      .sort((a, b) => b[0] - a[0])
      .forEach(([major, info]) => {
        if (latestMajor !== null && major === latestMajor) return;

        // Value points to the real patch folder (e.g., '12.0.3'), title shows the abstracted track name ('v12')
        items.push({ value: info.id, title: `v${major}` });
      });

    if (items.length === 0) {
      items.push({ value: activeFolderOnServer, title: activeFolderOnServer });
    }

    dynamicVersionItems.length = 0;
    items.forEach(i => dynamicVersionItems.push(i));
  }

  console.log(`➡ Current Server Active Folder: "${activeFolderOnServer}"`);
  console.log(`➡ Calculated Dropdown Options:`);
  console.table(dynamicVersionItems);

  console.log(`➡ Click Evaluation Outcomes:`);
  dynamicVersionItems.forEach(item => {
    const selectedVersion = item.value;
    let actionResult = '';

    if (activeFolderOnServer && activeFolderOnServer !== selectedVersion) {
      actionResult = `🔄 REDIRECT -> window.top.location.href = "/${repoName}/${selectedVersion}/"`;
    } else {
      actionResult = '✅ Match! User stays on current page.';
    }
    console.log(`   • Clicked "${item.title}" [Targets Folder: ${selectedVersion}]: ${actionResult}`);
  });
  console.log('\n==================================================\n');
}

runTestSuite();
